default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: admin
  password: admin
  timeout: 5000

development:
  <<: *default
  database: bilinho
test:
  <<: *default
  database: bilinho

production:
  <<: *default
  database: bilinho
  adapter: postgresql
  host: <%= ENV.fetch('172.17.0.1') %>
  port: <%= ENV.fetch('5432') %>
  username: <%= ENV.fetch('admin') %>
  password: <%= ENV.fetch('admin') %>